### ISSUE TITLE
Fix NullReferenceException at World browser

### ISSUE THREAD

**Issue by alexnadergikalo** [scellecs/morpeh#131]
There is NullReferenceException if I remove entity and crete it again at one System.

![photo_2022-09-12_10-52-14 (2)](https://user-images.githubusercontent.com/43637236/189711452-1b5cdf90-956e-4f16-a848-93d2144c686f.jpg)
![photo_2022-09-12_10-52-14](https://user-images.githubusercontent.com/43637236/189711461-8935e860-fe43-442a-b5f1-802151ad12a5.jpg)

**Comment by olegmrzv** [comment]
I can't reproduce the bug. Submit an example project.
