### ISSUE TITLE
Can't select bag for components with one boolean value

### ISSUE THREAD

**Issue by IgorTime** [scellecs/morpeh#134]
При попытке взять bag для компонента, в котором содерржиться только 1 булевое поле выдает ошибку.
`You Select<ECSAction> marker component from filter! This makes no sense.`

Предполагаю что ошибка в методе подсчета размера компонента. 
Простое добовление поля типа Int убрало ошибку 

![image](https://user-images.githubusercontent.com/29376604/192154519-e525dca4-c6a0-4c01-831f-aab507f2cc35.png)
![image](https://user-images.githubusercontent.com/29376604/192154540-1231d309-66c7-4814-af74-806fc61fb65b.png)
![image](https://user-images.githubusercontent.com/29376604/192154598-47e27f08-8baa-4bf5-96fb-95c7ea5de281.png)

**Comment by SH42913** [comment]
Баг с самой зари Морпеха. Связан с тем, что пустой структ занимает столько же памяти, сколько струк с одни булём. Из-за этого же бага, компонент с одним булём вообще не работает, тк Морпех не сохраняет его изменения, тк считает его маркером. Можно исправить компонент локально, добавив ещё один буль или любое другое поле.
@olegmrzv, или может добавить в Морпех какой-нибудь атрибут типа `DefinitelyNotAMarker`? :D
Стоит добавить в Readme раздел `Known Corner Cases` с упоминанием этой особенности Морпеха?

**Comment by olegmrzv** [comment]
в 2022 мажоре это исправлено
https://github.com/scellecs/morpeh/commit/f225ee8031526185897b75fa7f56ec9a4865d01b

я могу портануть этот фикс в 2020 версию

**Comment by olegmrzv** [comment]
https://github.com/scellecs/morpeh/pull/135
