### ISSUE TITLE
Namespace modification warning

### ISSUE THREAD

**Issue by SH42913** [scellecs/morpeh#145]
I've got this warning at first startup in **Unity 2020.3.41f1** for unknown reason, but it didn't lead to any other issues, everything works fine.
![image](https://user-images.githubusercontent.com/17111024/199064523-56e9765a-acb4-4c91-a2a1-71f2675245ac.png)

**Comment by olegmrzv** [comment]
Fixed in 4645f419e66ce1065df8e22e7529a917763219b9
