### ISSUE TITLE
ComponentsCacheDisposable doesn't work with AOT

### ISSUE THREAD

**Issue by SH42913** [scellecs/morpeh#146]
I've got error
```
ExecutionEngineException: Attempting to call method 'Morpeh.ComponentsCacheDisposable`1[[Tanks.GameInput.GameUser, Tanks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]::.ctor' for which no ahead of time (AOT) code was generated.
```
while trying to build [morpeh.examples.tanks](https://github.com/scellecs/morpeh.examples.tanks) for Windows with IL2CPP using Unity 2019.4.40f1.
But everything works fine, when I change ComponentsCacheDisposable visibility to public and call constructor directly from system's `OnAwake()`.

**Comment by olegmrzv** [comment]
Fixed in #152 
Commit SHA 6cdbb333a114db4858ab256cf7083014db757330
