### ISSUE TITLE
Dispose world issue.

### ISSUE THREAD

**Issue by L-LingRen** [scellecs/morpeh#170]
<img width="901" alt="Snipaste_2023-02-26_00-11-01" src="https://user-images.githubusercontent.com/42627496/221367432-7180e896-e93b-4747-83c9-30f99f48335e.png">
<img width="892" alt="Snipaste_2023-02-26_00-24-28" src="https://user-images.githubusercontent.com/42627496/221368012-ed35a077-195e-4d5c-bc61-b85a7548207f.png">

Perhaps in the future you can write some tip to "README.md" for this problem.
I spent a lot of time to trace this problem.

**Comment by olegmrzv** [comment]
thanks for your contribution.
this is definitely a bug and will be fixed soon for versions 2022.2 and 2023.1

**Comment by olegmrzv** [comment]
fixed in 2022.2.2 5d17cc73fe582dbab237f591123b94f285d6c126 on master branch
and 2023.1.0-rc16 bea3cc86cf80b8ec2408991ab664993ebca1ff53 on stage-2023.1 branch
