### ISSUE TITLE
Increase Update calls by += 1 each time a new world is created

### ISSUE THREAD

**Issue by russellGadel** [scellecs/morpeh#185]
The bug is observed on mobile devices.
The bug does't reproduce in Unity Editor(v 2021.3.11f1.)

Build apk.
Reproducing a bug:
1. Go to the Second scene
2. First time real and ecs time is same
3. Go back to the sample scene
4. Go to the Second scene, ecs time is going faster than real time

Example project: https://github.com/russellGadel/morpeh-issue/tree/master

**Comment by olegmrzv** [comment]
Fixed in 2023.1.0-rc56
