### ISSUE TITLE
[2023.1-rc] Incremental Generator for Aspects

### ISSUE THREAD

**Issue by kandreyc** [scellecs/morpeh#186]
I really like your version of ECS. Especially the new version with introduced aspects.
I've created a simple incremental generator to reduce boilerplate. Maybe will be useful for someone. 
https://github.com/kandreyc/Scellecs.Morpeh.SourceGenerator

> works in a version 2023.1 which is currently not final.
> works only with unity that supports incremental generator.
> better to use it under the asmdef where morpeh related code is located.

**Comment by olegmrzv** [comment]
Thanks for the contribution.
I'll add this to the documentation in the current release.
