### ISSUE TITLE
Make world disposing more safely

### ISSUE THREAD

**Issue by Car3man** [scellecs/morpeh#196]
It will get rid of checks to property "IsDisposed"
```
if (!_world.IsDisposed)
{
    _world.Dispose();
}
```
If try to dispose world few times it throws an error on trying to dispose systemGroups

Note from MSDN:
✓ DO allow the Dispose(bool) method to be called more than once. The method might choose to do nothing after the first call.

**Comment by olegmrzv** [comment]
Thanks for contribution.
It will be reworked in 2023.1.1

**Comment by olegmrzv** [comment]
Fixed in #2023.1.1-rc4
