### ISSUE TITLE
Hypercasual Example Project by Me

### ISSUE THREAD

**Issue by StinkySteak** [scellecs/morpeh#203]
Hello, I've made a simple sample learning project (Mobile Hypercasual). This is my first time using Morpeh beside quantum & unity dots as a ecs framework. Could you help me by
1. Add the project to the Samples in this repo?
2. Comment out what's good/bad in my samples?

Here's the repo: https://github.com/StinkySteak/unity-morpeh-hypercasual

I would say Morpeh is really convenient coming from dots & ecs background. I love the entity provider!

**Comment by olegmrzv** [comment]
Hi there, thanks for your contribution.
Unfortunately, there is no access to your repository, it seems to be private, and I can't give any feedback.

**Comment by StinkySteak** [comment]
My bad, just updated the repo to public!

**Comment by olegmrzv** [comment]
I would recommend moving the code into directories.
For example, systems into the Systems folder, components into the Components folder, and so on.
Now they are in one pile and it is confusing.

And overall it’s good.

**Comment by StinkySteak** [comment]
I've tidy the folders & Added a pull request!

Thanks for the help

**Comment by olegmrzv** [comment]
Merged.
