### ISSUE TITLE
World Browser does't work with Odin inspector

### ISSUE THREAD

**Issue by styrbo** [scellecs/morpeh#210]
![image](https://github.com/scellecs/morpeh/assets/120588143/58172bd7-d47f-41b2-969b-63d1a2d452c2)
unity version: 2022.3.15f1
odin version: 3.1.9.0
morpeh version: 2023.1.0

i got 2 exceptions:
- https://pastebin.com/8L0VTGB8
- `GUI Error: Invalid GUILayout state in  view. Verify that all layout Begin/End calls match
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

how to reproduce?
1) create new project
2) import odin
3) import morpeh
4) enter to playmode
unity project:
[TestOdin.zip](https://github.com/scellecs/morpeh/files/13822193/TestOdin.zip)

**Comment by Gallardo994** [comment]
Could you recheck it with Morpeh 2024.1.0-rc61? As there's a completely new World Browser, this bug could've been fixed there.
