### ISSUE TITLE
Working on a new sample

### ISSUE THREAD

**Issue by R1nge** [scellecs/morpeh#212]
I've started working on a new sample to showoff how to use ECS only for gameplay and manage the game state, so the main difference between my previous sample and this one would be a more advanced game state management. 
Also, is it worth it to keep my old one in the samples section? 
It's a bit outdated and I'm not planning to update it any time soon,

**Comment by R1nge** [comment]
Is it a good practice to do inject like that?
```
public class ShootingProvider : MonoProvider<ShootingComponent>
{
    [Inject] private BulletFactory _bulletFactory;

    protected override void Initialize()
    {
        Entity.GetComponent<ShootingComponent>().BulletFactory = _bulletFactory;
    }
}


public struct ShootingComponent : IComponent
{
    public BulletFactory BulletFactory;
}
```

**Comment by olegmrzv** [comment]
I think it’s worth leaving example until Morpeh version 2024.1 comes out.
What about injections, I recommend doing them inside systems, not providers.

**Comment by R1nge** [comment]
Thanks for the explanation.
When will 2024.1 come out?

**Comment by R1nge** [comment]
Well, that's a lot to cover. 
Definitely will be waiting for it. 
And would create another sample if I have time)
But for now, will continue working on a sample for the current version.
Don't close this issue please.
Will close when it's done.

**Comment by R1nge** [comment]
Almost finished the core of the game. 
it was really fun and I got a couple of new questions.

In one of previous replies you mentioned that it's possible to get data from a provider, so the data should be in IComponent, and all Unity stuff should go into provider, am I correct?

How to inject into systems?
I don't remember if Zenject can inject **into** scriptables, but VContainer definitely can't.
So, I had to create my own version of installer and inject like this:

My_ecs_installer.cs is an inheritor of Installer
```
[SerializeField] private OnDamageGameOverSystem onDamageGameOverSystem;
[Inject] private GameStateMachine _gameStateMachine; 

 private void Start()
 {
     onDamageGameOverSystem.Inject(_gameStateMachine);
 }
 ```
 
onDamageGameOverSystem.cs
 ```
 private GameStateMachine _gameStateMachine;
 public void Inject(GameStateMachine gameStateMachine) => _gameStateMachine = gameStateMachine; 
 ```

**Comment by R1nge** [comment]
It's done, 
I wanted to add some fancy graphics, SFX, etc. 
But it would a game, not an example.
Will create a pull request after your answers to my previous questions.

![Untitled](https://github.com/scellecs/morpeh/assets/59400159/ff5f23ac-f623-4fb8-9b0d-898cc1f3eb5e)

**Comment by olegmrzv** [comment]
It is better to create an InjectableInstaller into which the entire container is injected, and through the container the injection is called for systems (all or specific ones)

**Comment by R1nge** [comment]
It's definitely a smarter solution than mine. 
Just implemented and it looks much better.
Thanks for you time and help.
