### ISSUE TITLE
Add DISABLE_COMPILE_REPORT define support

### ISSUE THREAD

**Issue by Shad3rMan** [scellecs/morpeh#215]
Add DISABLE_COMPILE_REPORT define support to disable compilation time reporting each time scripts get recompiled.

**Comment by olegmrzv** [comment]
Fixed in [2023.1.1-rc12](https://github.com/scellecs/morpeh/tree/2023.1.1-rc12)
Define is **MORPEH_DISABLE_COMPILATION_REPORT**
