### ISSUE TITLE
Customizing System Group Updates in Morpeh for Network Synchronization in Online Games

### ISSUE THREAD

**Issue by AegeanRagdolls** [scellecs/morpeh#216]
Hello, we are using Morpeh, which is very lightweight and convenient. However, we have encountered some issues during our usage. We are developing a online game where both the server and client share the same set of business logic. However, when handling network synchronization, we hope that the update of system groups can be customized. For example, some groups handle multiple rollback snapshots and have a custom variable-speed update. Some groups are used for simulation and may not always update simultaneously. We attempted to modify the source code, but we are unsure if future versions will support custom update of system groups. Is there any way to meet our current needs without modifying the source code?

**Comment by SH42913** [comment]
You can create `SystemsGroup` and call `group.Update()` by yourself whenever you want.
Like I did it [here](https://github.com/SH42913/gunshotwound2/blob/3661e7bf634f51bfd18dbc189c802f8db4193cfc/GunshotWound2/GunshotWound2.cs#L137)

**Comment by AegeanRagdolls** [comment]
Thank you very much for your response, it perfectly solved the problem. Much appreciated! :)
