### ISSUE TITLE
A component is added to stash on creation

### ISSUE THREAD

**Issue by SSS135** [scellecs/morpeh#223]
When stash is created, a component is automatically added to it in the constructor. This component is not bound to any entity which makes `Stash.IsEmpty()` return false even when no entity with that component does exists in a world.

This line:
`this.components.Add(-1, default, out _);`
https://github.com/scellecs/morpeh/blob/2eb519ce4a4c3d0cc3096e92d0db1166aa69d88a/Core/Stash.cs#L141C13-L141C53

Is it necessary? If so, `Stash.IsEmpty()` and `Stash.IsNotEmpty()` functions are meaningless.

**Comment by olegmrzv** [comment]
Fixed in 2023.1.1
If you need it right now you can switch on stage-2023.1
Btw 2023.1.1 version will be released by the end of the month
