### ISSUE TITLE
SizeOf<T> Issue

### ISSUE THREAD

**Issue by AIEternity** [scellecs/morpeh#55]
Unity 2021.1.14 Unity.Collections.LowLevel.Unsafe.UnsafeUtility.SizeOf<T>() возвращает неверный результат для компонента с одним булевым полем из-за чего тип помечается как маркер. System.Runtime.InteropServices.Marshal.SizeOf(default(T)) отрабатывает как надо.

**Comment by olegmrzv** [comment]
Да, спасибо за репорт.
Баг исправлен в подготовке к 9 мажору.
https://github.com/scellecs/Morpeh/commit/f225ee8031526185897b75fa7f56ec9a4865d01b
